Vagrant.configure("2") do |config|
  config.vm.define 'tcc-gector-api' do |debian|
      config.vm.box = "bento/ubuntu-20.04"
      debian.vm.network :private_network, ip: '192.168.100.100'
      debian.vm.hostname = 'tcc-gector-api'

      config.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh", disabled: true
      config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
      config.vm.network :forwarded_port, guest: 22, host: 2245, auto_correct: true
      config.ssh.port = 2245

      config.vm.provider "virtualbox" do |vb|
          vb.memory = "8192"
          vb.cpus = "4"
      end

      config.vm.provision "ansible" do |ansible|
          ansible.become = true
          ansible.verbose = 'v'
          ansible.playbook = './gector-setup.yml'
      end
  end
end
