Vagrant.configure("2") do |config|
  config.vm.define 'client-simulator' do |debian|
      config.vm.box = "bento/ubuntu-20.04"
      debian.vm.network :private_network, ip: '192.168.100.105'
      debian.vm.hostname = 'client-simulator'

      config.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh", disabled: true
      config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
      config.vm.network :forwarded_port, guest: 22, host: 2345, auto_correct: true
      config.ssh.port = 2345

      config.vm.provider "virtualbox" do |vb|
          vb.memory = "2048"
          vb.cpus = "2"
      end

      config.vm.provision "ansible" do |ansible|
          ansible.become = true
          ansible.verbose = 'v'
          ansible.playbook = './client-simulator-setup.yml'
          ansible.compatibility_mode = "2.0"
      end
  end
end
