---
- hosts: tcc-gector-api
  become: yes
  vars_files:
    - vars/main.yml

  handlers:
    - name: restart cron
      ansible.builtin.service:
        name: cron
        state: restarted

  pre_tasks:
    - name: add python repository from PPA
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Set timezone to America/Recife
      community.general.timezone:
        name: America/Recife
      notify: restart cron

    - name: install apt dependencies
      ansible.builtin.apt:
        pkg: '{{ apt_pkgs }}'
        cache_valid_time: 3600
        update_cache: true

    - name: upgrade python dependencies
      ansible.builtin.pip:
        virtualenv_python: python3.7
        name:
          - pip
          - setuptools
        extra_args: --upgrade

  roles:
    - name: manala.roles.ngrok
    - name: cloudalchemy.node_exporter

  tasks:
    - name: configure ngrok
      ansible.builtin.command:
        cmd: ngrok config add-authtoken {{ vault_ngrok_token }}
      become_user: vagrant

    - name: clone gector-api
      ansible.builtin.git:
        repo: https://github.com/elaynelemos/gector-api.git
        dest: &app_dir /var/www/gector-api
        separate_git_dir: /srv/gector-api.git
        version: master
        update: yes
        single_branch: yes

    - name: append user vagrant www-data group
      ansible.builtin.user:
        name: vagrant
        groups: &app_user www-data
        append: yes

    - name: create python virtual environment
      command:
        cmd: python3.7 -m venv /var/www/gector-api/.venv
        creates: /var/www/gector-api/.venv

    - name: install python dependencies at the virtualenv
      ansible.builtin.pip:
        requirements: requirements.txt
        chdir: *app_dir
        virtualenv: .venv
        virtualenv_command: python3.7 -m venv

    - name: ensures application user permissions
      ansible.builtin.file:
        path: *app_dir
        state: directory
        recurse: yes
        owner: *app_user
        group: *app_user
