---
- hosts: local
  become: yes
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: install apt dependencies
      ansible.builtin.apt:
        pkg: '{{ apt_pkgs }}'
        cache_valid_time: 3600
        update_cache: true

  roles:
    - name: manala.roles.ngrok

  tasks:
    - name: configure ngrok
      ansible.builtin.command:
        cmd: ngrok config add-authtoken {{ vault_ngrok_token }}
