---
- hosts: tcc-gector-api
  become: yes
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: install apt dependencies
      ansible.builtin.apt:
        pkg: '{{ apt_pkgs }}'
        cache_valid_time: 3600
        update_cache: true

  roles:
    - name: manala.roles.ngrok

  tasks:
    - name: configure ngrok
      ansible.builtin.command:
        cmd: ngrok config add-authtoken {{ vault_ngrok_token }}

    - name: Clone gector-api
      ansible.builtin.git:
        repo: https://github.com/elaynelemos/gector-api.git
        dest: /var/www/gector-api
        single_branch: yes
        version: master
