---
- hosts: local
  become: yes

  pre_tasks:
    - name: install apt dependencies
      ansible.builtin.apt:
        pkg: '{{ apt_pkgs }}'
        cache_valid_time: 3600
        update_cache: true
    
    - name: install pip dependencies
      ansible.builtin.pip:
        name: Flask==2.2.2

  roles:
    - name: manala.roles.ngrok
