---
collections:
  - name: community.general
    version: 4.5.0
  - name: ansible.posix
    version: 1.3.0

roles:
  - name: cloudalchemy.node_exporter
    src: https://github.com/4linux/ansible-node-exporter.git
    scm: git
    version: cddc25fd8f8e8bebb3aff12e1a71ac5ddf950b59
  - name: oefenweb.swapfile
    version: v2.0.35
