Vagrant.configure("2") do |config|
  config.vm.define 'tcc-gector-api' do |debian|
      config.vm.box = "bento/ubuntu-20.04"
      debian.vm.network :private_network, ip: '192.168.100.100'
      debian.vm.hostname = 'tcc-gector-api'

      config.vm.provider "virtualbox" do |vb|
          vb.memory = "7000"
          vb.cpus = "4"
      end

      config.vm.provision "ansible" do |ansible|
          ansible.become = true
          ansible.playbook = "./gector-setup.yml"
          ansible.ask_vault_pass = true
      end
  end
end
